version: "3"

volumes:
    gmsdata:

services:
    web:
        image: gms_web
        restart: unless-stopped
        build:
            context: ./
            args:
                dev_dependencies: "${DEV_DEPENDENCIES}"
        entrypoint: /code/entrypoint.sh
        command: "gunicorn geomapshark.wsgi -b :9000 --error-logfile gunicorn_log.log --workers=2 --threads=4 --worker-class=gthread"
        volumes:
            - ${PRIVATE_DOCUMENTS_DIR}:/private_documents
        ports:
            - "${DJANGO_DOCKER_PORT}:9000"
        networks:
            - pdf_generation
            - default

    # Builder for the geocity_qgis image.
    # Containers will be started on demand by Django, meaning that runtime config
    # will be ignored
    qgis:
        image: geocity_qgis
        build:
            context: services/qgis

    pdf:
        restart: unless-stopped
        build:
            context: services/pdf
        networks:
            - pdf_generation
        environment:
            WEB_ROOT_URL: http://web:9000

networks:
    # custom network to restriction communication to between django<->pdf
    pdf_generation:
