version: "3"

volumes:
    gmsdata:

services:
    web:
        image: gms_web
        restart: unless-stopped
        build:
            context: ./
            args:
                dev_dependencies: "${DEV_DEPENDENCIES}"
        entrypoint: /code/entrypoint.sh
        command: "gunicorn geomapshark.wsgi -b :9000 --error-logfile gunicorn_log.log --workers=2 --threads=4 --worker-class=gthread"
        volumes:
            - ${PRIVATE_DOCUMENTS_DIR}:/private_documents
            - ${ARCHIVE_DIR}:/archive
        ports:
            - "${DJANGO_DOCKER_PORT}:9000"
        networks:
            - isolated
            - default

    # Builder for the geocity_qgis image.
    qgis:
        image: geocity_qgis
        build:
            context: services/qgis
        # This service is only there for building, containers are instantaited on demand by Django.
        # Runtime config below is therefore ignored.
        # networks:
        #     - isolated

    # Builder for the geocity_pdf image
    pdf:
        image: geocity_pdf
        build:
            context: services/pdf
        # This service is only there for building, containers are instantaited on demand by Django.
        # Runtime config below is therefore ignored.
        # networks:
        #     - isolated

networks:
    # Use this for containers that should only be able to communicate with Django
    isolated:
        name: geocity_isolated
