# Generated by Django 4.1.4 on 2023-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0018_alter_sectionparagraph_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectiondetail",
            name="undesired_properties",
            field=models.CharField(
                blank=True,
                help_text="Liste de détails à supprimer, séparés par des virgules ',' correspondant aux titre des détails (ex: hauteur,largeur)",
                max_length=2000,
                null=True,
                verbose_name="Détails à supprimer",
            ),
        ),
    ]
