name: Geocity CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Lint Code"
      uses: pre-commit/action@v3.0.0
    - name: Build/Pull Containers
      run: cp env.demo .env && docker-compose build
    - name: Run Containers
      run: docker-compose down --remove-orphans && docker-compose up -d
    - name: Sanity Checks
      run: |
        WEB_OK=$(docker ps -aq --filter status="running" --filter name="geocity_web_1") && if [ -z "$WEB_OK" ]; then exit 1; fi
        POSTGRES_OK=$(docker ps -aq --filter status="running" --filter name="geocity_postgres_1") && if [ -z "$POSTGRES_OK" ]; then exit 1; fi
        QGISSERVER_OK=$(docker ps -aq --filter status="running" --filter name="geocity_qgisserver_1") && if [ -z "$QGISSERVER_OK" ]; then exit 1; fi
    - name: "Wait for Postgres"
      run: docker-compose exec -T postgres pg_isready --timeout=10
    - name: "Test Code"
      run: docker-compose exec -T web ./run_tests.sh
    - name: Stop Containers
      run: docker-compose down --remove-orphans
