name: Geocity CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Lint Code"
      uses: pre-commit/action@v3.0.0

    - name: Configure stack
      run: cp env.demo .env

    - name: Build/Pull Containers
      run: docker-compose build

    - name: Start Postgres
      run: docker-compose up -d postgres

    - name: Wait for Postgres
      run: docker-compose exec -T postgres pg_isready --timeout=30

    - name: Run tests (with 2FA)
      env:
        ENABLE_2FA: "true"
      run: |
        docker-compose run --service-ports --name=web --rm --entrypoint="" web coverage run --source='.' ./manage.py test --settings=geomapshark.settings_test --keepdb

    - name: Coverage report (with 2FA)
      run: docker-compose run --rm --entrypoint="" web coverage report -m

    - name: Run tests (without 2FA)
      env:
        ENABLE_2FA: "false"
      run: |
        docker-compose run --service-ports --name=web --rm --entrypoint="" web coverage run --source='.' ./manage.py test --settings=geomapshark.settings_test --keepdb

    - name: Coverage report (without 2FA)
      run: docker-compose run --rm --entrypoint="" web coverage report -m
