name: Geocity CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build/Pull Containers
      run: cp env.demo .env && docker-compose -f docker-compose-dev.yml build
    - name: Run Containers
      run: docker-compose -f docker-compose-dev.yml down --remove-orphans && docker-compose -f docker-compose-dev.yml up -d
    - name: Sanity Checks
      run: |
        WEB_OK=$(docker ps -aq --filter status="running" --filter name="geocity_web_1") && if [ -z "$WEB_OK" ]; then exit 1; fi
        POSTGRES_OK=$(docker ps -aq --filter status="running" --filter name="geocity_postgres_1") && if [ -z "$POSTGRES_OK" ]; then exit 1; fi
    - name: "Lint Code"
      run: docker-compose -f docker-compose-dev.yml exec -T web black . --check
    - name: "Test Code"
      run: docker-compose -f docker-compose-dev.yml exec -T web ./run_tests.sh
    - name: Stop Containers
      run: docker-compose -f docker-compose-dev.yml down --remove-orphans
